### ISSUE TITLE
Choose License type

### ISSUE THREAD

**Issue by ilhan-mstf** [EmakinaTR/makina-app#11]
- [x] [Choose an open source license type](https://choosealicense.com/)
- [x] Add license file to repo

**Comment by koraytaylan** [comment]
I have also been reading about this. It feels like we should make a choice between MIT and Apache License 2.0
Elasticsearch can be a role model for us. They use Apache License https://github.com/elastic/elasticsearch/blob/master/LICENSE.txt

**Comment by ilhan-mstf** [comment]
+1 Apache would be fine since anyone who use this product should also distrubute the source code.

**Comment by koraytaylan** [comment]
Apache it is then 👍 We need a volunteer for updating the license 😄
